[en]
major = "{note} major"
minor = "{note_lower} minor"
mode = "{note} {mode}"

[en.modes]
dor = "Dorian"
phr = "Phrygian"
lyd = "Lydian"
mix = "Mixolydian"
loc = "Locrian"

[de]
major = "{note}-Dur"
minor = "{note_lower}-Moll"
mode = "{note}-{mode}"

[de.modes]
dor = "Dorisch"
phr = "Phrygisch"
lyd = "Lydisch"
mix = "Mixolydisch"
loc = "Lokrisch"

[de.notes]
C = "C"
"C#" = "Cis"
Cb = "Ces"
Cbb = "Ceses"
"C##" = "Cisis"
Cx = "Cisis"
D = "D"
"D#" = "Dis"
Db = "Des"
Dbb = "Deses"
"D##" = "Disis"
Dx = "Disis"
E = "E"
"E#" = "Eis"
Eb = "Es"
Ebb = "Eses"
"E##" = "Eisis"
Ex = "Eisis"
F = "F"
"F#" = "Fis"
Fb = "Fes"
Fbb = "Feses"
"F##" = "Fisis"
Fx = "Fisis"
G = "G"
"G#" = "Gis"
Gb = "Ges"
Gbb = "Geses"
"G##" = "Gisis"
Gx = "Gisis"
A = "A"
"A#" = "Ais"
Ab = "As"
Abb = "Ases"
"A##" = "Aisis"
Ax = "Aisis"
B = "H"
"B#" = "His"
Bb = "B"
Bbb = "Heses"
"B##" = "Hisis"
Bx = "Hisis"
